//Category=Microservice Platforms, Kubernetes, AKS, ACI, ARO
//Platform=Azure
//Maturity level=Initial

:toc: macro
toc::[]
:idprefix:
:idseparator: -

== Microservice Platforms
=== Azure

This chapter lists major features/ concrete services for microservices platforms within Azure. A detailed discussion of services is part of the solution design based on a certain service.

Azure provides the following container platforms:

* Azure Kubernetes Service (AKS)
+
--
It represents a hosted Kubernetes service. Additional features on  *orchestration platform* include the integration with other Azure services such as Azure Active Directory concepts.
--
* Azure Container Instance (ACI)
+
--
This service is intended to run single containers without native orchestration support. However, it can be integrated into Kubernetes.
--
* Azure Red Hat OpenShift (ARO)
+
--
It provides highly available, fully managed OpenShift clusters as *orchestration platform* on demand, monitored and operated jointly by Microsoft and Red Hat. Kubernetes is at the core of Red Hat OpenShift. OpenShift brings added-value features to complement Kubernetes, making it a turnkey container platform as a service (PaaS) with a significantly improved developer and operator experience.
--

Regarding *the applications to be deployed* Azure comes also with its own Azure container reistry (ACR).
