//Category=Stream Processing
//Platform=Azure
//Maturity level=Complete

:toc: macro
toc::[]
:idprefix:
:idseparator: -

== Stream Processing Platforms

=== Azure

==== Overview

This chapter lists major features/ concrete services for stream processing on the Azure platform. This architecture pattern builds on the general problem description for stream processing.

https://docs.microsoft.com/en-us/azure/architecture/data-guide/technology-choices/stream-processing[In Azure], all of the following data stores will meet the core requirements supporting real-time processing:

* Azure Stream Analytics
* HDInsight with Spark Streaming (Microbacth processing)/ Kafka Streaming (Stream processing)
* Apache Spark (Microbacth processing) in Azure Databricks
* HDInsight with Storm (Stream processing)
* Azure Functions
* Azure App Service WebJobs
* Apache Kafka streams API

For Kafka a separate page with guidelines exists. https://docs.microsoft.com/en-us/azure/architecture/data-guide/technology-choices/stream-processing[The Azure Docs] provide tables with decision criteria for the following technology options: Azure Stream Analytics, HDInsight with Spark Streaming, Apache Spark in Azure Databricks, HDInsight with Storm, Azure Functions, Azure App Service WebJobs.