//Category=Storage
//Products=types of cloud storage
//Maturity level=Initial

----

= Cloud Storage

== Cloud Storage

This article mainly focuses on below topics:
- what is cloud storage?
- How does it works?
- Benefits of cloud storage
- Cloud storage requirement
- Types of Cloud Storage
- Use cases

=== What is cloud storage?

Cloud storage is a cloud computing model in which data is transmitted and stored on remote storage systems, where it is maintained, managed, backed up and made available to users over a network -- typically, the internet.
It’s delivered on demand with just-in-time capacity and costs, and eliminates buying and managing your own data storage infrastructure. This gives you agility, global scale and durability, with “anytime, anywhere” data access.

=== How does it works?

Cloud storage is purchased from a third party cloud vendor who owns and operates data storage capacity and delivers it over the Internet in a pay-as-you-go model. Typically, you connect to the storage cloud either through the internet or a dedicated private connection, using a web portal, website, or a mobile app. The server with which you connect forwards your data to a pool of servers located in one or more data centers, depending on the size of the cloud provider’s operation.Applications access cloud storage through traditional storage protocols or directly via an API.
These cloud storage vendors manage capacity, security and durability to make data accessible to your applications all around the world.

Cloud storage is available in private, public and hybrid clouds.

- Public cloud storage: In this model, you connect over the internet to a storage cloud that’s maintained by a cloud provider and used by other companies.
- Private cloud storage: Private cloud storage setups typically replicate the cloud model, but they reside within your network, leveraging a physical server to create instances of virtual servers to increase capacity. You can choose to take full control of an on-premise private cloud or engage a cloud storage provider to build a dedicated private cloud that you can access with a private connection.
- Hybrid cloud storage: This model combines elements of private and public clouds, giving organizations a choice of which data to store in which cloud.

==== Benefits of cloud storage

* Total Cost of Ownership:
 With cloud storage, there is no hardware to purchase, storage to provision, or capital being used for "someday" scenarios. You can add or remove capacity on demand, quickly change performance and retention characteristics, and only pay for storage that you actually use. 
 Less frequently accessed data can even be automatically moved to lower cost tiers in accordance with auditable rules, driving economies of scale.

 * Time to Deployment:
 Cloud storage allows IT to quickly deliver the exact amount of storage needed, right when it's needed. This allows IT to focus on solving complex application problems instead of having to manage storage systems.

 * Information Management:
  Centralizing storage in the cloud creates a tremendous leverage point for new use cases. By using cloud storage lifecycle management policies, you can perform powerful information management tasks including automated tiering or locking down data in support of compliance requirements.

  * Scalability: Growth constraints are one of the most severe limitations of on-premise storage. With cloud storage, you can scale up as much as you need. Capacity is virtually unlimited.


==== Limitations of Cloud storage

* Security: Security concerns are common with cloud-based services. Cloud storage providers try to secure their infrastructure with up-to-date technologies and practices,but occasional breaches have occurred, creating discomfort with users. Security is shared responsibility with cloud providers and users.

* Latency: Delays in data transmission to and from the cloud can occur as a result of traffic congestion, especially when you use shared public internet connections.

* Regulatory compilance: Certain industries, such as healthcare and finance, have to comply with strict data privacy and archival regulations, which may prevent companies from using cloud storage for certain types of files, such as medical and investment records.

==== Type of Cloud storage

Majorly, below are main types of cloud storage:

* Object Storage: It manages data as objects.  Each object includes the data in a file, its associated metadata, and an identifier. Objects store data in the format it arrives in and makes it possible to customize metadata in ways that make the data easier to access and analyze. Instead of being organized in files or folder hierarchies, objects are kept in repositories that deliver virtually unlimited scalability. Since there is no filing hierarchy and the metadata is customizable, object storage allows you to optimize storage resources in a cost-effective way.

* File Storage: The file storage method saves data in the hierarchical file and folder structure with which most of us are familiar. The data retains its format, whether residing in the storage system or in the client where it originates, and the hierarchy makes it easier and more intuitive to find and retrieve files when needed. File storage is commonly used for development platforms, home directories, and repositories for video, audio, and other files.

* Block Storage: Block storage, sometimes referred to as block-level storage, is a technology that is used to store data files on Storage Area Networks (SANs) or cloud-based storage environments. Developers favor block storage for computing situations where they require fast, efficient, and reliable data transportation.Block storage breaks up data into blocks and then stores those blocks as separate pieces, each with a unique identifier. The SAN places those blocks of data wherever it is most efficient. 
Block storage also decouples data from user environments, allowing that data to be spread across multiple environments. This creates multiple paths to the data and allows the user to retrieve it quickly.

Also, archival and database services can be considered for data storage

=== Products & Services

Below table contains services from different cloud vendors:

[cols="1,1,1,1"]
|===
|Vendor|	Storage Services|	Database Services	|Backup Services

|AWS
|• Simple Storage Service (S3) +
• Elastic Block Storage (EBS) +
• Elastic File System (EFS) +
• Storage Gateway +
• Snowball +
• Snowball Edge +
• Snowmobile 
|	• Aurora +
• RDS +
• DynamoDB +
• ElastiCache +
• Redshift +
• Neptune	
|Glacier

|Azure
|• Blob Storage +
• Queue Storage +
• File Storage +
•  Disk Storage +
• Data Lake Store
|	•SQL Database +
• Database for MySQL +
• Database for PostgreSQL +
• Data Warehouse +
• Server Stretch Database +
• Cosmos DB +
• Table Storage +
• Redis Cache +
• Data Factory 
|• Archive Storage +
• Backup +
• Site Recovery

|GCP
|•Cloud Storage +
• Persistent Disk +
• Transfer Appliance +
• Transfer Service 
|	•Cloud SQL +
• Cloud Bigtable +
• Cloud Spanner +
• Cloud Datastore
|None
|===


=== References:

https://www.ibm.com/cloud/learn/cloud-storage#toc-what-is-cl-vt64lltQ
https://aws.amazon.com/what-is-cloud-storage/ 