//Category=Storage
//Product=Storage
//Maturity level=Initial

= Cloud Storage

== Cloud Storage

This article mainly focuses on below topics:
- What is Cloud Storage?
- How does it works?
- Benefits of Cloud Storage
- Cloud Storage requirement
- Types of Cloud Storage
- Product and services offered by different vendors

=== What is Cloud Storage?

Cloud Storage is a cloud computing model in which data is transmitted and stored on remote storage systems, where it is maintained, managed, backed up and made available to users over a network -- typically, the internet.
It’s delivered on demand with just-in-time capacity and costs, and eliminates buying and managing your own data storage infrastructure. This gives you agility, global scale and durability, with “anytime, anywhere” data access.

=== How does it works?

Cloud Storage is purchased from a third party cloud vendor who owns and operates data storage capacity and delivers it over the Internet in a pay-as-you-go model. Typically, you connect to the storage cloud either through the internet or a dedicated private connection, using a web portal, website, or a mobile app. The server with which you connect forwards your data to a pool of servers located in one or more data centers, depending on the size of the cloud provider’s operation.Applications access Cloud Storage through traditional storage protocols or directly via an API.
These Cloud Storage vendors manage capacity, security and durability to make data accessible to your applications all around the world.

Cloud Storage is available in private, public and hybrid clouds.

- Public Cloud Storage: In this model, you connect over the internet to a storage cloud that’s maintained by a cloud provider and used by other companies.
- Private Cloud Storage: Private Cloud Storage setups typically replicate the cloud model, but they reside within your network, leveraging a physical server to create instances of virtual servers to increase capacity. You can choose to take full control of an on-premise private cloud or engage a Cloud Storage provider to build a dedicated private cloud that you can access with a private connection.
- Hybrid Cloud Storage: This model combines elements of private and public clouds, giving organizations a choice of which data to store in which cloud.

==== Benefits of Cloud Storage

* Total Cost of Ownership:
 With Cloud Storage, there is no hardware to purchase, storage to provision, or capital being used for "someday" scenarios. You can add or remove capacity on demand, quickly change performance and retention characteristics, and only pay for storage that you actually use. 
 Less frequently accessed data can even be automatically moved to lower cost tiers in accordance with auditable rules, driving economies of scale.

 * Time to Deployment:
 Cloud Storage allows IT to quickly deliver the exact amount of storage needed, right when it's needed. This allows IT to focus on solving complex application problems instead of having to manage storage systems.

 * Information Management:
  Centralizing storage in the cloud creates a tremendous leverage point for new use cases. By using Cloud Storage lifecycle management policies, you can perform powerful information management tasks including automated tiering or locking down data in support of compliance requirements.

  * Scalability: Growth constraints are one of the most severe limitations of on-premise storage. With Cloud Storage, you can scale up as much as you need. Capacity is virtually unlimited.


==== Limitations of Cloud Storage

* Security: Security concerns are common with cloud-based services. Cloud Storage providers try to secure their infrastructure with up-to-date technologies and practices,but occasional breaches have occurred, creating discomfort with users. Security is shared responsibility with cloud providers and users.

* Latency: Delays in data transmission to and from the cloud can occur as a result of traffic congestion, especially when you use shared public internet connections.

* Regulatory compilance: Certain industries, such as healthcare and finance, have to comply with strict data privacy and archival regulations, which may prevent companies from using Cloud Storage for certain types of files, such as medical and investment records.

==== Type of Cloud Storage

Majorly, below are main types of Cloud Storage:

|===
|Storage |Description |Services

|Object storage
a|* Data is stored as object. Each object includes the data in a file, its associated metadata, and an identifier.
* Metadata can be customized and detailed.
*	Objects store data in the format it arrives in
*	Instead of files and folders data is stored in repositories.
*	Provides unlimited scalability
*	Cost effective option
*	Use cases:
  
It’s a storage system well suited for static data, and its agility and flat nature means it can scale to extremely large quantities of data. The objects have     enough information for an application to find the data quickly and are good at storing unstructured data.

*	Cons:
 -	Object can't be modified
 -	doesn't work well with traditional db


|AWS- Simple storage service(S3)
Azure- Blob storage
GCP – Google cloud storage


|File storage
a|*	File storage method saves data in the hierarchical file and folder structure
*	The data retains its format
*	Easy to find and retrieve files when needed
*	Single path exists for each file
*	Use cases:
File storage is commonly used for development platforms, home directories, and repositories for video, audio, and other files.
*	Cons:
  -	Inconsistency in data format.
  -	The same information being kept in several different places (files)
  -	Data inconsistency, a situation where various copies of the same data are conflicting, wastes storage space and duplicates effort.
|AWS – 
EFS and FSx Azure-
Azure file storage 
GCP-
Google Cloud Filestore 


|Block storage
a|*	Block-level storage is a technology that is used to store data files on Storage Area Networks (SANs) or cloud-based storage environments.
*	Block storage breaks up data into blocks and then stores those blocks as separate pieces, each with a unique identifier.
*	Block storage also decouples data from user environments, allowing that data to be spread across multiple environments.
*	Creates multiple paths to the data and allows the user to retrieve it quickly
*	Use cases:
  -	Developers block storage for computing situations where they require fast, efficient, and reliable data transportation.
  -	It works well with enterprises performing big transactions and those that deploy huge databases, meaning the more data you need to store, the better off you’ll be with block storage.
*	cons:
  -	expensive
  -	limited capability to handle metadata
|EBS in AWS and Google Cloud Persistent Disks in GCP.

|Database
a|Each cloud provider have there own fully managed services.
More about 

* AWS database - https://aws.amazon.com/products/databases/
* Azure database – 
 https://azure.microsoft.com/en-in/product-categories/databases/
* GCP -  https://cloud.google.com/docs 
|

|Archival
|Archival storage services are used when user want to store data which is not frequently accessed. This are generally available at lowest cost. This service can be used for backing up data.
|AWS – S3 Glacier
Azure- Azure Archive storage
GCP 
GCP – Storage classes
|===


=== Products & Services

Below table contains services from different cloud vendors:

[cols="1,1,1,1"]
|===
|Vendor|	Storage Services|	Database Services	|Backup Services

|AWS
|• Simple Storage Service (S3) +
• Elastic Block Storage (EBS) +
• Elastic File System (EFS) +
• Storage Gateway +
• Snowball +
• Snowball Edge +
• Snowmobile 
|• Aurora +
• RDS +
• DynamoDB +
• ElastiCache +
• Redshift +
• Neptune	
|Glacier

|Azure
|• Blob Storage +
• Queue Storage +
• File Storage +
• Disk Storage +
• Data Lake Store
|	• SQL Database +
• Database for MySQL +
• Database for PostgreSQL +
• Data Warehouse +
• Server Stretch Database +
• Cosmos DB +
• Table Storage +
• Redis Cache +
• Data Factory 
|• Archive Storage +
• Backup +
• Site Recovery

|GCP
|• Cloud Storage +
• Persistent Disk +
• Transfer Appliance +
• Transfer Service 
|	• Cloud SQL +
• Cloud Bigtable +
• Cloud Spanner +
• Cloud Datastore
|None
|===


=== References:

https://www.ibm.com/cloud/learn/cloud-storage#toc-what-is-cl-vt64lltQ

https://aws.amazon.com/what-is-cloud-storage/ 
