== HTTP application routing in Azure: 
The HTTP application routing add-on is designed to let you quickly create an ingress controller and access your applications. 
This add-on is not currently designed for use in a production environment and is not recommended for production use. 

Following steps to enable HTTP application routing.

. Enable HTTP routing on existing AKS cluster using the `az aks enable-addons` with the Azure CLI

	az aks enable-addons --resource-group myResourceGroup --name myAKSCluster --addons http_application_routing
	

. use the `az aks show` command to retrieve the DNS zone name.
  
  az aks show --resource-group myResourceGroup --name myAKSCluster --query addonProfiles.httpApplicationRouting.config.HTTPApplicationRoutingZoneName -o table
	
. Adding annotations

	annotations:
		kubernetes.io/ingress.class: addon-http-application-routing
	
. Change your ingress host with http application DNS Zone name.  

	host: xxxxx.xxxxxx.xxxx.region.aksapp.io
	
== Nginx-ingress-controller-setup:

Install Nginx ingress controller in kubernetes cluster by using helm chart.

* Adding the Helm repository, if you’re installing the chart via the helm repository.

	helm repo add bitnami https://charts.bitnami.com/bitnami

* Upgrading the Chart

	helm repo update

* Installing the Chart
If you have Helm, you can deploy the ingress controller with the following command:

AWS - EKS:

	helm upgrade --install nginx-ingress nginx-ingress-controller --set ingressClassResource.default=true --set containerSecurityContext.allowPrivilegeEscalation=false --repo https://charts.bitnami.com/bitnami --namespace nginx-ingress --create-namespace

AZURE - AKS:

	helm install nginx-stable nginx-stable/nginx-ingress --set controller.setAsDefaultIngress=true --namespace nginx-ingress --create-namespace 
	
== Examples
=== Providing Dynamic Values to Helm chart
When installing Helm charts with the helm install command, the `--set` argument allows you to define value in a values.yaml file, `application.cloud` is deployment  environment, aws or azure, `ingress.application.host` is to set host value.

	helm install otlp ./helm --set application.cloud="AWS" --set ingress.application.host="xxx.com"

